<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7RMACVL" failures="1" tests="6" name="testng.failtestcases.SoftAssertionExample" time="63.832" errors="0" timestamp="2024-07-04T17:40:14 IST" skipped="3">
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_3" time="13.021"/>
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_1" time="9.946">
    <failure message="The following asserts failed:
	Text should be Create a Rediffmail account expected [create a Rediffmail account] but found [Create a Rediffmail account]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Text should be Create a Rediffmail account expected [create a Rediffmail account] but found [Create a Rediffmail account]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testng.failtestcases.SoftAssertionExample.softAssert_1(SoftAssertionExample.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- softAssert_1 -->
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_1" time="5.992">
    <skipped/>
  </testcase> <!-- softAssert_1 -->
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_1" time="7.828">
    <skipped/>
  </testcase> <!-- softAssert_1 -->
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_1" time="7.568">
    <skipped/>
  </testcase> <!-- softAssert_1 -->
  <testcase classname="testng.failtestcases.SoftAssertionExample" name="softAssert_2" time="19.477"/>
</testsuite> <!-- testng.failtestcases.SoftAssertionExample -->
